# Generated by Django 5.1.6 on 2025-03-23 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_user_remove_product_image_payment_delete_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='user_id',
            new_name='user',
        ),
    ]
