# Generated by Django 5.1.6 on 2025-03-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_user_name_user_password_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='sentiment',
            field=models.IntegerField(choices=[(0, 'Negative'), (1, 'Positive')], default=1),
        ),
    ]
