# Generated by Django 5.1.7 on 2025-03-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_payment_comment_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order_date',
            field=models.DateTimeField(),
        ),
    ]
