# Generated by Django 5.2 on 2025-04-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_payment_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_purchase',
            field=models.BooleanField(default=True),
        ),
    ]
