# Generated by Django 5.1.7 on 2025-03-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_payment_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='type',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
